### ISSUE TITLE
Migrate to CircleCI 2.0 *before* August 31st

### ISSUE THREAD

**Issue by stephendonner** [mozilla/servicebook-web#168]
We need to migrate to CircleCI 2.0: "This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0."

https://circleci.com/docs/2.0/migration/

**Comment by davehunt** [comment]
This was done in https://github.com/mozilla/servicebook-web/commit/fe751cd4495e871414bf62ccba3ee7ce99d64873 and some followups.

**Comment by stephendonner** [comment]
Thanks again, @davehunt !
