### ISSUE TITLE
OIDC callback failures in stage, with incomplete/missing submissions to Sentry

### ISSUE THREAD

**Issue by karlht** [mozilla/servicebook-web#181]
Two login failures, both using Mozilla LDAP auth.  Both fail the OIDC callback dance.

Apparently the Sentry IDs don't actually show up in Sentry.

Callback URLs and Sentry IDs available on request.

**Comment by ckolos** [comment]
sample error:
[pid: 17|app: 0|req: 4/13] 127.0.0.1 () {48 vars in 1254 bytes} [Mon Aug 27 17:26:14 2018] GET /oidc/callback?code=<BAR>&state=<FOO> => generated 2560 bytes in 474 msecs (HTTP/1.0 500) 6 headers in 381 bytes (1 switches on core 0)

**Comment by ckolos** [comment]
@karlht I need tarek for this; apologies for not getting this fixed for you. I'll drop him an email and set up a time for tomorrow

**Comment by karlht** [comment]
He's on PTO at the moment, as far as I know.  I'm not sure when he's scheduled to come back; it doesn't seem to be in luded on any of the calendars I'm subscribed to.

**Comment by davehunt** [comment]
Is there anything I can do to help?
