### ISSUE TITLE
Static assets not being served

### ISSUE THREAD

**Issue by karlht** [mozilla/servicebook-web#185]
Logged in, did Auth0 OIDC dance, was logged in correctly.

Attempted to edit description for Lockbox (project 48), hit Submit, and got "Oops, something went wrong"

Sentry Event ID: 6caf9c4603304bd3b68e7defb836ce37

**Comment by tarekziade** [comment]
you tried while we were deploying ;)

can you try now @karlht  ?

**Comment by karlht** [comment]
Editing now works, but the static CSS is not being served -- I get an unstyled page.

**Comment by karlht** [comment]
From IRC: 
```
oh yeah once I empty the cache its 404 for me too
ckolos: ^  https://servicebook.stage.mozaws.net/static/css/bookstyle.css <- 404
```

**Comment by ckolos** [comment]
Fixed. Problem with the static resource copying script.

**Comment by karlht** [comment]
Confirmed working now.  Thanks, Chris!
