### ISSUE TITLE
Active checkbox makes project inactive

### ISSUE THREAD

**Issue by rbillings** [mozilla/servicebook-web#187]
When editing, all projects have the Active checkbox de-selected, and yet some have an Active status and others do not. Checking and saving the active checkbox makes the project Inactive, instead of Active.

**Comment by tarekziade** [comment]
Let's close it once @davehunt tried it and it works on his side

**Comment by davehunt** [comment]
I can confirm that this is working for me. I'd like to get #192 fixed before we deploy a new version.

**Comment by davehunt** [comment]
New version deployed, and I've confirmed this is fixed.
