### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/servicebook-web#225]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/servicebook-web/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by davehunt** [comment]
Thanks. The wiki can be disabled for this repository as it is not used. I do not appear to have the necessary access to make this change.

**Comment by ghost** [comment]
disabled -- thanks for the followup!
