### ISSUE TITLE
Fix typos/clarify code comment in util.py

### ISSUE THREAD

**Issue by stephendonner** [mozilla/servicebook-web#26]
This comment could use clarification/typo-fixing :-)

https://github.com/mozilla/servicebook-web/blob/bc166af2520ebab68442e1ff9b29506def627337/serviceweb/util.py#L11

Not sure what ```# XXX projects.tests theneck if completed and 8 test``` is trying to say.

**Comment by tarekziade** [comment]
I think that's a weird paste - will remove, thx
