### ISSUE TITLE
Allow nginx to be disabled via ENV setting

### ISSUE THREAD

**Issue by ckolos** [mozilla/servicebook-web#35]
For deployments, cloudops runs a local nginx process that conflicts with the nginx process included in the container. I am able to get around this in deployment by templating the supervisor.conf and replacing it via a docker volume config, but long term, it's probably better to have an option to disable the in-container nginx in favor of an external web server, if not remove nginx from the container entirely.

**Comment by tarekziade** [comment]
Nginx was removed from the Docker
