### ISSUE TITLE
serve the __version__ route from the application not via a nginx config

### ISSUE THREAD

**Issue by ckolos** [mozilla/servicebook-web#36]
In the app, the \_\_version\_\_ endpoint is being served via a nginx config mapping the \_\_version\_\_ location to the file /app/version.json. While this is fine when the container is running nginx, as mentioned in #35, if the containers nginx process isn't running or being used, the \_\_version\_\_ endpoint is no longer available.

**Comment by tarekziade** [comment]
The __version__ endpoint is served by the app as well for that reason.

https://github.com/mozilla/servicebook-web/blob/master/serviceweb/views/heartbeat.py#L10

So if you proxy the app you should get access to it as well

**Comment by tarekziade** [comment]
Closing as invalid. Feel free to reopen
