### ISSUE TITLE
version.json contains invalid build information

### ISSUE THREAD

**Issue by ckolos** [mozilla/servicebook-web#43]
Once the docker image has been built, the version.json contains travis-ci's build url/infomation, not circle's:
curl https://servicebook.<endpoint>/__version__
{                                                                                                                                   
  "build": "https://travis-ci.org/mozilla/servicebook", 
  "commit": "", 
  "source": "https://github.com/mozilla/servicebook", 
  "version": "2.0"
}

The "build" var should contain the circle build corresponding to the image deployed, not the travis build of the github repo.

**Comment by ckolos** [comment]
Docs for the spec are [here](https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md]). It states "CI Tool" but for our practices in stage/prod, this is expected to and needs to be the circle build.

**Comment by tarekziade** [comment]
Fixed and verified in circle-ci
